workspace: ./logs/dreamfusion_lego_with_albedo_2
# experiment base setting
comment: 'test lego with albedo all the time'
O_machine: true
cuda_ray: true
dir_text: true

# guidance setting
guidance: stable-diffusion
text: 'a lego man'

# NeRF setting
# Training Setting
iters: 20000
albedo: true
jitter_pose: true