workspace: ./logs/dreamfusion_superman_riding_horses
# experiment base setting
comment: 'test superman with Imporved Magic3D'
O_machine: true
cuda_ray: true
dir_text: true
seed: 2023

# guidance setting
guidance: stable-diffusion
# text: 'A bulldog is wearing a black pirate hat.'
text: 'a superman riding a horse'

# NeRF setting
# Training Setting
iters: 20000
jitter_pose: true
fullres: true
scale_num: 2