# experiment base setting
workspace: ./logs/flower_inpainting_test
O_machine: true

# data setting
datadir: /data5/wuzhongkai/data/dreamfusion_data/llff/nerf_llff_data_504x360_centre_mask/flower 
dataset_type: llff
dir_text: False

#resolution in training, test and guidance
h: 90
w: 126
h_guidance: 360
w_guidance: 504
H: 360
W: 504

# guidance setting
guidance: stable-diffusion-inpainting
text: 'a high quality photo of a red flower'

# NeRF setting
# Training Setting
iters: 15000