workspace: ./logs/dreamfusion_bunny_fullres
# experiment base setting
comment: 'test superman with Imporved Magic3D'
O_machine: true
cuda_ray: true
dir_text: true

# guidance setting
guidance: stable-diffusion
# text: 'A bulldog is wearing a black pirate hat.'
text: 'a baby bunny sitting on top of a stack of pancakes'

# dataset setting
w: 64
h: 64
w_guidance: 512
h_guidance: 512
H: 512
W: 512

# NeRF setting
# Training Setting
iters: 20000
jitter_pose: true
full_resolution: false 
scale_num: 8