workspace: ./logs/dreamfusion_castle_4
# experiment base setting
O_machine: true

# guidance setting
guidance: stable-diffusion
text: 'A highly detailed sandcastle'

# NeRF setting
# Training Setting
iters: 20000