workspace: ./logs/dreamfusion_vintage_car_with_shading
# experiment base setting
comment: 'test vintage car with shading all the time'
O_machine: true
cuda_ray: true
dir_text: true

# guidance setting
guidance: stable-diffusion
# text: 'A bulldog is wearing a black pirate hat.'
text: 'an old vintage car'

# NeRF setting
# Training Setting
iters: 20000
jitter_pose: true