workspace: ./logs/dreamfusion_robotichand
# experiment base setting
O_machine: true

# guidance setting
guidance: stable-diffusion
text: 'A robot hand, realistic'

# NeRF setting
# Training Setting
iters: 20000