workspace: ./logs/dreamfusion_superman
# experiment base setting
O_machine: true
cuda_ray: true
dir_text: true
save_mesh: true

# guidance setting
guidance: stable-diffusion
text: 'A high quality sand castle'

# NeRF setting
# Training Setting
iters: 20000
albedo: true
jitter_pose: true