workspace: ./logs/dreamfusion_bunny_3
# experiment base setting
comment: 'test superman with Imporved Magic3D'
O_machine: true
cuda_ray: true
dir_text: true

# guidance setting
guidance: stable-diffusion
# text: 'A bulldog is wearing a black pirate hat.'
text: 'a baby bunny sitting on top of a stack of pancakes'

# NeRF setting
# Training Setting
iters: 20000
jitter_pose: true