workspace: ./logs/dreamfusion_rendered_pig
# experiment base setting
O_machine: true
cuda_ray: true
dir_text: true

# guidance setting
guidance: stable-diffusion
text: 'A high quality rendered pig'

# NeRF setting
# Training Setting
iters: 20000
albedo: true
jitter_pose: true