# experiment base setting
workspace: ./logs/reconstruction_l2h
comment: 'test instant-ngp full model'
O_machine: true
cuda_ray: false

# data setting
datadir: /data5/wuzhongkai/data/dreamfusion_data/llff/nerf_llff_data_lr2hr/flower 
dataset_type: llff
bound: 2
N_rand: 1024

# resolution setting
w: 512 
h: 512 
W: 512 
H: 512 

# guidance setting
guidance: reconstruction
# NeRF setting
backbone: grid_full
optim: adam
bg_radius: 0

# Training Setting
iters: 15000
eval_interval: 10 
lr: 1e-2
min_lr: 1e-3
warm_iters: 100
albedo: True
lambda_entropy: 0
lambda_opacity: 0
lambda_orient: 0
lambda_tv: 0